from sqlalchemy import Column

from sqlalchemy import Integer

from sqlalchemy import String

from sqlalchemy import DateTime

from backend.app.database.database import Base

class Event(Base):

    """

    A single persisted mission event — a Battery drop, a subsystem

    Recovery, or a newly-triggered Warning/Critical alarm. Generated by

    backend/app/core/events.py and written from

    backend/app/routers/telemetry.py, immediately after the triggering

    telemetry sample is stored.

    Deliberately does NOT have a row for every telemetry packet ("Telemetry

    received" events): only anomalies are persisted here. The dashboard's

    Mission Timeline still shows a "Telemetry received" row for every

    packet, exactly as before, but generates that one entirely

    client-side — see pushTimelineEvents() in frontend/js/dashboard.js —

    since it isn't an anomaly and persisting one row for it every few

    seconds forever would bloat this table with routine noise instead of

    meaningful history.

    This is a brand-new table, not a new column on an existing one, so no

    entry in backend/app/database/migrations.py is needed for it —

    Base.metadata.create_all() (see backend/app/main.py) already creates

    any table that doesn't exist yet, on both a fresh database and an

    existing one that only has the older `telemetry` table so far.

    """

    __tablename__ = "events"

    id = Column(

        Integer,

        primary_key=True,

        index=True

    )

    satellite_id = Column(

        String,

        nullable=False,

        index=True

    )

    timestamp = Column(

        DateTime,

        nullable=False,

        index=True

    )

    # "Battery" | "Recovery" | "Warning" | "Critical" — matches the Mission

    # Timeline event types already used in frontend/js/dashboard.js, so the

    # frontend can pass this value straight into its existing

    # addTimelineEvent() unchanged.

    event_type = Column(

        String,

        nullable=False

    )

    # Alarm severity ("Warning"/"Critical") for alarm-sourced events; None

    # for Battery and Recovery events, which are not alarm-classified. For

    # alarm-sourced events this is currently always equal to `event_type`

    # — kept as its own column anyway (rather than reusing event_type) so

    # GET /events can filter on severity independently of the more

    # detailed event_type vocabulary, per the API's own filtering

    # requirements.

    severity = Column(

        String,

        nullable=True

    )

    message = Column(

        String,

        nullable=False

    )

    # Stable, machine-readable identifier for what triggered this event —

    # e.g. "power_critical" (from the alarm that triggered it),

    # "battery_drop", or "power_recovery". Always populated (every event

    # type has one), unlike `subsystem` below.

    rule = Column(

        String,

        nullable=False

    )

    # Which subsystem this event relates to, if any — e.g. "power". None

    # for events with no specific subsystem (e.g. a CPU load alarm, which

    # has no corresponding subsystem — see METRIC_SUBSYSTEM_OVERLAP in

    # backend/app/core/alarms.py).

    subsystem = Column(

        String,

        nullable=True

    )