"""

Telemetry endpoints: receiving new telemetry samples and retrieving the

most recently stored sample or a paginated, filterable history of samples.

"""

from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException, Query, status

from sqlalchemy.exc import SQLAlchemyError

from sqlalchemy.orm import Session

from backend.app.core.alarms import evaluate_alarms, log_alarms

from backend.app.core.events import generate_events

from backend.app.core.health_status import worst_status

from backend.app.core.logging_config import get_logger

from backend.app.database.dependencies import get_db

from backend.app.models.telemetry import Telemetry

from backend.app.schemas.events import EventResponse

from backend.app.schemas.telemetry import (

    TelemetryCreate,

    TelemetryCreatedResponse,

    TelemetryResponse,

)

from backend.app.websocket.connection_manager import manager

router = APIRouter(tags=["Telemetry"])

logger = get_logger(__name__)

@router.post(

    "/telemetry",

    response_model=TelemetryCreatedResponse,

    status_code=status.HTTP_200_OK,

    summary="Receive a telemetry packet",

    description=(

        "Receives a single telemetry packet generated by a satellite or by "

        "this project's telemetry simulator, computes its overall status "

        "from its subsystem health (see health_status.worst_status()), "

        "persists it to the database, evaluates it against the alarm rules "

        "in backend/app/core/alarms.py, derives any newly-occurring mission "

        "events by comparing it against the satellite's previous sample "

        "(see backend/app/core/events.py — persisted to the `events` table "

        "and retrievable later via `GET /events`), and broadcasts the "

        "sample — together with its computed status, alarms, and any new "

        "events — to every connected WebSocket client (see `/ws`) for live "

        "dashboard updates."

    ),

    operation_id="receive_telemetry",

    responses={

        200: {

            "description": "Telemetry was validated, stored, and broadcast successfully.",

            "content": {

                "application/json": {

                    "example": {"message": "Telemetry stored successfully", "id": 52}

                }

            },

        },

        422: {

            "description": (

                "The telemetry packet failed validation — for example, a "

                "coordinate or percentage field is out of its allowed "

                "range, or `subsystems` is missing an expected key."

            ),

        },

        500: {

            "description": "The telemetry packet was valid but could not be stored due to a database error.",

            "content": {

                "application/json": {

                    "example": {

                        "detail": "A database error occurred while storing the telemetry record."

                    }

                }

            },

        },

    },

)

async def create_telemetry(

    telemetry: TelemetryCreate,

    db: Session = Depends(get_db)

) -> TelemetryCreatedResponse:

    logger.info("Telemetry received from %s", telemetry.satellite_id)

    # Fetched BEFORE constructing/adding the new sample, so event

    # generation (below) compares "what changed since last time" without

    # comparing the new row against itself. None for a satellite's

    # first-ever sample — generate_events() still logs a Warning/Critical

    # alarm present on that very first sample (see the "First-sample

    # anomalies" section of that module's docstring); only the Battery and

    # Recovery event checks require a genuine previous value to exist.

    previous_telemetry = (

        db.query(Telemetry)

        .filter(Telemetry.satellite_id == telemetry.satellite_id)

        .order_by(Telemetry.timestamp.desc())

        .first()

    )

    # The backend is the single source of truth for overall status: the

    # client (TelemetryCreate) reports only per-subsystem health, never an

    # overall status directly — see the module docstring in

    # backend/app/schemas/telemetry.py for why a client-supplied value

    # would be a second, potentially-inconsistent source of truth for the

    # same fact `subsystems` already reports.

    computed_status = worst_status(telemetry.subsystems.values())

    db_telemetry = Telemetry(

        satellite_id=telemetry.satellite_id,

        latitude=telemetry.latitude,

        longitude=telemetry.longitude,

        altitude=telemetry.altitude,

        velocity=telemetry.velocity,

        timestamp=telemetry.timestamp,

        battery=telemetry.battery,

        temperature=telemetry.temperature,

        signal_strength=telemetry.signal_strength,

        cpu_load=telemetry.cpu_load,

        status=computed_status,

        subsystems=telemetry.subsystems

    )

    # Alarms and derived mission events are computed BEFORE the commit

    # below, entirely from values already in memory (telemetry.subsystems/

    # battery/etc. on the object just constructed above, and

    # previous_telemetry fetched above) — none of it needs db_telemetry.id,

    # so none of it needs a flush first. That's what makes it possible to

    # add the telemetry row and every event it produces to the session

    # together and commit exactly once, below.

    alarms = evaluate_alarms(db_telemetry)

    # evaluate_alarms() is called a second time here, against

    # previous_telemetry, purely so generate_events() can diff "which

    # alarm rules are new" — it does not re-evaluate anything against

    # db_telemetry a second time, and does not duplicate any threshold

    # logic (see backend/app/core/events.py's module docstring).

    previous_alarms = (

        evaluate_alarms(previous_telemetry) if previous_telemetry is not None else []

    )

    new_events = generate_events(db_telemetry, previous_telemetry, alarms, previous_alarms)

    # Single transaction: the telemetry sample and every mission event it

    # produces are added to the session together and committed once, so

    # they succeed or fail as one atomic unit. This project's core

    # requirement — "every anomaly stored" — would not hold if telemetry

    # could be durably saved while its derived event silently failed to

    # be; a prior version of this endpoint committed them in two separate

    # transactions and is the reason this comment exists.

    db.add(db_telemetry)

    db.add_all(new_events)

    try:

        db.commit()

    except SQLAlchemyError:

        db.rollback()

        logger.exception(

            "Database commit failed while storing telemetry and its "

            "derived mission events for %s",

            telemetry.satellite_id

        )

        raise HTTPException(

            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,

            detail="A database error occurred while storing the telemetry record.",

        )

    db.refresh(db_telemetry)

    for event in new_events:

        db.refresh(event)

    logger.info(

        "Telemetry stored in database (id=%s, satellite=%s, status=%s, events=%d)",

        db_telemetry.id,

        db_telemetry.satellite_id,

        db_telemetry.status,

        len(new_events)

    )

    # Logged only now, after the commit above has actually succeeded —

    # logging an alarm/event as "recorded" before the transaction that

    # persists it is confirmed durable would be misleading if that commit

    # then failed.

    log_alarms(alarms, logger)

    message = {

        "id": db_telemetry.id,

        "satellite_id": db_telemetry.satellite_id,

        "latitude": db_telemetry.latitude,

        "longitude": db_telemetry.longitude,

        "altitude": db_telemetry.altitude,

        "velocity": db_telemetry.velocity,

        "timestamp": db_telemetry.timestamp.isoformat(),

        "battery": db_telemetry.battery,

        "temperature": db_telemetry.temperature,

        "signal_strength": db_telemetry.signal_strength,

        "cpu_load": db_telemetry.cpu_load,

        "status": db_telemetry.status,

        "subsystems": db_telemetry.subsystems,

        "alarms": [alarm.model_dump() for alarm in alarms],

        "events": [EventResponse.model_validate(event).model_dump(mode="json") for event in new_events]

    }

    await manager.broadcast(message)

    return {

        "message": "Telemetry stored successfully",

        "id": db_telemetry.id

    }

@router.get(

    "/telemetry/latest",

    response_model=TelemetryResponse,

    status_code=status.HTTP_200_OK,

    summary="Get the latest telemetry sample",

    description=(

        "Returns the most recently stored telemetry record — including its "

        "backend-computed overall status, its per-subsystem health, and "

        "any alarms it currently triggers (see "

        "backend/app/core/alarms.py). Intended for dashboard and browser "

        "clients that need an immediate snapshot on load, before the first "

        "live update arrives over `/ws` — and for the Chrome extension, "

        "which polls this endpoint instead of using the WebSocket.\n\n"

        "If no telemetry has been stored yet, this returns **HTTP 404** "

        "with a descriptive `detail` message."

    ),

    operation_id="get_latest_telemetry",

    responses={

        200: {

            "description": "The latest telemetry record.",

            "content": {

                "application/json": {

                    "example": {

                        "id": 52,

                        "satellite_id": "SD-CUBESAT-001",

                        "latitude": 8.9832,

                        "longitude": -79.5199,

                        "altitude": 408.42,

                        "velocity": 7.66,

                        "timestamp": "2026-07-27T18:35:12Z",

                        "battery": 98.4,

                        "temperature": 22.5,

                        "signal_strength": 94.8,

                        "cpu_load": 28.1,

                        "status": "Nominal",

                        "subsystems": {

                            "power": "Nominal",

                            "thermal": "Nominal",

                            "communications": "Nominal",

                            "adcs": "Nominal",

                            "payload": "Nominal",

                        },

                        "alarms": [],

                    }

                }

            },

        },

        404: {

            "description": "No telemetry has been recorded yet.",

            "content": {

                "application/json": {

                    "example": {"detail": "No telemetry has been recorded yet."}

                }

            },

        },

        500: {

            "description": "A database error occurred while querying for the latest telemetry.",

            "content": {

                "application/json": {

                    "example": {

                        "detail": "A database error occurred while retrieving the latest telemetry record."

                    }

                }

            },

        },

    },

)

def get_latest_telemetry(

    db: Session = Depends(get_db)

) -> TelemetryResponse:

    try:

        latest = (

            db.query(Telemetry)

            .order_by(Telemetry.timestamp.desc())

            .first()

        )

    except SQLAlchemyError:

        logger.exception("Database query failed while fetching latest telemetry")

        raise HTTPException(

            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,

            detail="A database error occurred while retrieving the latest telemetry record.",

        )

    if latest is None:

        logger.warning("No telemetry found in database")

        raise HTTPException(

            status_code=status.HTTP_404_NOT_FOUND,

            detail="No telemetry has been recorded yet.",

        )

    # Re-evaluated on every read rather than read back from storage: alarm

    # thresholds (backend/app/core/config.py) can change between when a

    # sample was stored and when it's read, and re-evaluating is exactly

    # as cheap as the numeric comparisons in evaluate_alarms() — there is

    # nothing worth caching. `evaluate_alarms()` itself tolerates a legacy

    # row's `subsystems=None` (see the defensive `or {}` in

    # backend/app/core/alarms.py) — it's simply treated as "no subsystem

    # data available," not a crash, so `latest` is passed straight through

    # with no special-casing needed here. Unlike POST /telemetry, this

    # does NOT call log_alarms(): logging belongs to the moment telemetry

    # arrives, not to every subsequent read of it (the Chrome extension

    # polls this endpoint every few seconds, which would otherwise flood

    # the logs).

    alarms = evaluate_alarms(latest)

    return {

        "id": latest.id,

        "satellite_id": latest.satellite_id,

        "latitude": latest.latitude,

        "longitude": latest.longitude,

        "altitude": latest.altitude,

        "velocity": latest.velocity,

        "timestamp": latest.timestamp,

        "battery": latest.battery,

        "temperature": latest.temperature,

        "signal_strength": latest.signal_strength,

        "cpu_load": latest.cpu_load,

        "status": latest.status,

        "subsystems": latest.subsystems,

        "alarms": alarms

    }

def _query_telemetry_records(

    db: Session,

    *,

    limit: int,

    offset: int,

    from_: datetime | None,

    to: datetime | None,

    satellite_id: str | None = None,

    status_filter: str | None = None,

    battery_lt: float | None = None,

    battery_lte: float | None = None,

    battery_gt: float | None = None,

    battery_gte: float | None = None,

) -> list[Telemetry]:

    """

    Shared SQLAlchemy query logic for both `GET /telemetry` and

    `GET /telemetry/history` — the two endpoints are the same operation

    (list the telemetry collection, paginated and optionally filtered)

    exposed at two paths, so the query itself is built exactly once here.

    Validates the `from`/`to` range (raising `HTTPException(400)` for an

    invalid combination) and applies whichever filters were actually

    supplied — date range, satellite ID, status, and/or battery

    comparisons — as a single, combined (AND-ed) query, ordering

    newest-first and applying offset/limit. Database errors are

    intentionally left to propagate as `SQLAlchemyError` — each caller

    wraps its own call to this function so it can log and raise its own

    endpoint-appropriate 500 `detail` message, matching the pattern

    already used for `POST /telemetry` and `GET /telemetry/latest`.

    `status_filter` (not `status`) to avoid shadowing the `fastapi.status`

    module already used in this function for `HTTPException` status codes.

    """

    if from_ is not None and to is not None:

        try:

            invalid_range = from_ > to

        except TypeError:

            # One of the two has a UTC offset (e.g. a trailing "Z") and the

            # other doesn't, so they can't be compared. A 400 here is

            # clearer to the client than an unhandled 500.

            raise HTTPException(

                status_code=status.HTTP_400_BAD_REQUEST,

                detail=(

                    "'from' and 'to' must both be timezone-aware or both "

                    "be naive — a value with a UTC offset (e.g. a "

                    "trailing 'Z') cannot be compared with one that has "

                    "none."

                ),

            )

        if invalid_range:

            raise HTTPException(

                status_code=status.HTTP_400_BAD_REQUEST,

                detail="The 'from' timestamp must not be after the 'to' timestamp.",

            )

    query = db.query(Telemetry)

    if from_ is not None:

        query = query.filter(Telemetry.timestamp >= from_)

    if to is not None:

        query = query.filter(Telemetry.timestamp <= to)

    if satellite_id is not None:

        query = query.filter(Telemetry.satellite_id == satellite_id)

    if status_filter is not None:

        query = query.filter(Telemetry.status == status_filter)

    if battery_lt is not None:

        query = query.filter(Telemetry.battery < battery_lt)

    if battery_lte is not None:

        query = query.filter(Telemetry.battery <= battery_lte)

    if battery_gt is not None:

        query = query.filter(Telemetry.battery > battery_gt)

    if battery_gte is not None:

        query = query.filter(Telemetry.battery >= battery_gte)

    return (

        query

        .order_by(Telemetry.timestamp.desc())

        .offset(offset)

        .limit(limit)

        .all()

    )

@router.get(

    "/telemetry/history",

    response_model=list[TelemetryResponse],

    status_code=status.HTTP_200_OK,

    summary="List historical telemetry records",

    description=(

        "Returns stored telemetry records ordered by timestamp, newest "

        "first, with `limit`/`offset` pagination and optional `from`/`to` "

        "date-range and attribute filtering (`satellite_id`, `status`, "

        "`battery_lt`/`battery_lte`/`battery_gt`/`battery_gte`). Intended "

        "for dashboard history views, mission analysis tooling, and other "

        "consumers that need more than the single most recent sample "

        "returned by `GET /telemetry/latest`.\n\n"

        "**All supplied filters are combined with AND.** For example, "

        "`?satellite_id=SD-CUBESAT-001&status=Critical&battery_lt=35&"

        "from=2026-07-20T00:00:00Z&to=2026-07-27T00:00:00Z` returns only "

        "records that satisfy every one of those conditions at once, in a "

        "single database query.\n\n"

        "**`GET /telemetry` is now the preferred, canonical way to list "

        "this same collection** — this endpoint is kept for backward "

        "compatibility and behaves identically.\n\n"

        "An empty result — no telemetry stored yet, or no records match "

        "the given filters — is a normal outcome for a collection "

        "endpoint and returns **HTTP 200** with an empty array, unlike "

        "`GET /telemetry/latest`, which returns 404 because it addresses "

        "a single resource rather than a collection."

    ),

    operation_id="get_telemetry_history",

    responses={

        200: {

            "description": "Zero or more telemetry records matching the given filters, newest first.",

            "content": {

                "application/json": {

                    "example": [

                        {

                            "id": 52,

                            "satellite_id": "SD-CUBESAT-001",

                            "latitude": 8.98,

                            "longitude": -79.52,

                            "altitude": 408.4,

                            "velocity": 7.66,

                            "timestamp": "2026-07-27T18:35:12Z",

                            "battery": 98.4,

                            "temperature": 22.5,

                            "signal_strength": 94.8,

                            "cpu_load": 28.1,

                            "status": "Nominal",

                        }

                    ]

                }

            },

        },

        400: {

            "description": "'from' is after 'to', or the two cannot be compared (mismatched timezone awareness).",

            "content": {

                "application/json": {

                    "example": {

                        "detail": "The 'from' timestamp must not be after the 'to' timestamp."

                    }

                }

            },

        },

        422: {

            "description": (

                "A query parameter failed validation — for example, `limit` "

                "outside its allowed range, an unparsable `from`/`to` date, "

                "an empty `satellite_id`/`status`, or a `battery_lt`/"

                "`battery_lte`/`battery_gt`/`battery_gte` value outside 0–100."

            ),

        },

        500: {

            "description": "A database error occurred while querying telemetry history.",

            "content": {

                "application/json": {

                    "example": {

                        "detail": "A database error occurred while retrieving telemetry history."

                    }

                }

            },

        },

    },

)

def get_telemetry_history(

    limit: int = Query(

        100,

        ge=1,

        le=1000,

        description="Maximum number of records to return.",

        examples=[50],

    ),

    offset: int = Query(

        0,

        ge=0,

        description="Number of matching records to skip, for pagination.",

        examples=[100],

    ),

    from_: datetime | None = Query(

        None,

        alias="from",

        description="Return only records with a timestamp greater than or equal to this value (ISO 8601).",

        examples=["2026-07-20T00:00:00Z"],

    ),

    to: datetime | None = Query(

        None,

        description="Return only records with a timestamp less than or equal to this value (ISO 8601).",

        examples=["2026-07-27T00:00:00Z"],

    ),

    satellite_id: str | None = Query(

        None,

        min_length=1,

        description="Return only records from this satellite.",

        examples=["SD-CUBESAT-001"],

    ),

    status_filter: str | None = Query(

        None,

        alias="status",

        min_length=1,

        description=(

            "Return only records with this exact satellite health status "

            '(e.g. "Nominal", "Warning", "Critical").'

        ),

        examples=["Critical"],

    ),

    battery_lt: float | None = Query(

        None,

        ge=0,

        le=100,

        description="Return only records with battery percentage strictly less than this value.",

        examples=[40.0],

    ),

    battery_lte: float | None = Query(

        None,

        ge=0,

        le=100,

        description="Return only records with battery percentage less than or equal to this value.",

        examples=[40.0],

    ),

    battery_gt: float | None = Query(

        None,

        ge=0,

        le=100,

        description="Return only records with battery percentage strictly greater than this value.",

        examples=[80.0],

    ),

    battery_gte: float | None = Query(

        None,

        ge=0,

        le=100,

        description="Return only records with battery percentage greater than or equal to this value.",

        examples=[80.0],

    ),

    db: Session = Depends(get_db),

) -> list[TelemetryResponse]:

    try:

        return _query_telemetry_records(

            db,

            limit=limit,

            offset=offset,

            from_=from_,

            to=to,

            satellite_id=satellite_id,

            status_filter=status_filter,

            battery_lt=battery_lt,

            battery_lte=battery_lte,

            battery_gt=battery_gt,

            battery_gte=battery_gte,

        )

    except SQLAlchemyError:

        logger.exception("Database query failed while fetching telemetry history")

        raise HTTPException(

            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,

            detail="A database error occurred while retrieving telemetry history.",

        )

@router.get(

    "/telemetry",

    response_model=list[TelemetryResponse],

    status_code=status.HTTP_200_OK,

    summary="List telemetry records",

    description=(

        "Returns stored telemetry records ordered by timestamp, newest "

        "first, with `limit`/`offset` pagination and optional `from`/`to` "

        "date-range and attribute filtering (`satellite_id`, `status`, "

        "`battery_lt`/`battery_lte`/`battery_gt`/`battery_gte`). This is "

        "the canonical, RESTful way to list the telemetry collection — a "

        "`GET` on the collection resource `/telemetry`.\n\n"

        "**All supplied filters are combined with AND.** For example, "

        "`?satellite_id=SD-CUBESAT-001&status=Critical&battery_lt=35&"

        "from=2026-07-20T00:00:00Z&to=2026-07-27T00:00:00Z` returns only "

        "records that satisfy every one of those conditions at once, in a "

        "single database query.\n\n"

        "`GET /telemetry/history` remains available and behaves "

        "identically; it is kept for backward compatibility with existing "

        "integrations, but new clients should prefer this endpoint.\n\n"

        "An empty result — no telemetry stored yet, or no records match "

        "the given filters — is a normal outcome for a collection "

        "endpoint and returns **HTTP 200** with an empty array, unlike "

        "`GET /telemetry/latest`, which returns 404 because it addresses "

        "a single resource rather than a collection."

    ),

    operation_id="list_telemetry",

    responses={

        200: {

            "description": "Zero or more telemetry records matching the given filters, newest first.",

            "content": {

                "application/json": {

                    "example": [

                        {

                            "id": 52,

                            "satellite_id": "SD-CUBESAT-001",

                            "latitude": 8.98,

                            "longitude": -79.52,

                            "altitude": 408.4,

                            "velocity": 7.66,

                            "timestamp": "2026-07-27T18:35:12Z",

                            "battery": 98.4,

                            "temperature": 22.5,

                            "signal_strength": 94.8,

                            "cpu_load": 28.1,

                            "status": "Nominal",

                        }

                    ]

                }

            },

        },

        400: {

            "description": "'from' is after 'to', or the two cannot be compared (mismatched timezone awareness).",

            "content": {

                "application/json": {

                    "example": {

                        "detail": "The 'from' timestamp must not be after the 'to' timestamp."

                    }

                }

            },

        },

        422: {

            "description": (

                "A query parameter failed validation — for example, `limit` "

                "outside its allowed range, an unparsable `from`/`to` date, "

                "an empty `satellite_id`/`status`, or a `battery_lt`/"

                "`battery_lte`/`battery_gt`/`battery_gte` value outside 0–100."

            ),

        },

        500: {

            "description": "A database error occurred while querying telemetry records.",

            "content": {

                "application/json": {

                    "example": {

                        "detail": "A database error occurred while retrieving telemetry records."

                    }

                }

            },

        },

    },

)

def get_telemetry(

    limit: int = Query(

        100,

        ge=1,

        le=1000,

        description="Maximum number of records to return.",

        examples=[50],

    ),

    offset: int = Query(

        0,

        ge=0,

        description="Number of matching records to skip, for pagination.",

        examples=[100],

    ),

    from_: datetime | None = Query(

        None,

        alias="from",

        description="Return only records with a timestamp greater than or equal to this value (ISO 8601).",

        examples=["2026-07-20T00:00:00Z"],

    ),

    to: datetime | None = Query(

        None,

        description="Return only records with a timestamp less than or equal to this value (ISO 8601).",

        examples=["2026-07-27T00:00:00Z"],

    ),

    satellite_id: str | None = Query(

        None,

        min_length=1,

        description="Return only records from this satellite.",

        examples=["SD-CUBESAT-001"],

    ),

    status_filter: str | None = Query(

        None,

        alias="status",

        min_length=1,

        description=(

            "Return only records with this exact satellite health status "

            '(e.g. "Nominal", "Warning", "Critical").'

        ),

        examples=["Critical"],

    ),

    battery_lt: float | None = Query(

        None,

        ge=0,

        le=100,

        description="Return only records with battery percentage strictly less than this value.",

        examples=[40.0],

    ),

    battery_lte: float | None = Query(

        None,

        ge=0,

        le=100,

        description="Return only records with battery percentage less than or equal to this value.",

        examples=[40.0],

    ),

    battery_gt: float | None = Query(

        None,

        ge=0,

        le=100,

        description="Return only records with battery percentage strictly greater than this value.",

        examples=[80.0],

    ),

    battery_gte: float | None = Query(

        None,

        ge=0,

        le=100,

        description="Return only records with battery percentage greater than or equal to this value.",

        examples=[80.0],

    ),

    db: Session = Depends(get_db),

) -> list[TelemetryResponse]:

    try:

        return _query_telemetry_records(

            db,

            limit=limit,

            offset=offset,

            from_=from_,

            to=to,

            satellite_id=satellite_id,

            status_filter=status_filter,

            battery_lt=battery_lt,

            battery_lte=battery_lte,

            battery_gt=battery_gt,

            battery_gte=battery_gte,

        )

    except SQLAlchemyError:

        logger.exception("Database query failed while listing telemetry")

        raise HTTPException(

            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,

            detail="A database error occurred while retrieving telemetry records.",

        )