"""
Pydantic schemas for the /telemetry endpoints.

`TelemetryCreate` is the request body accepted by `POST /telemetry`.
`TelemetryCreatedResponse` and `TelemetryResponse` describe the success
response shapes so Swagger/OpenAPI documents them precisely instead of
showing an untyped dict. Error responses (404 when no telemetry exists,
500 on a database failure) are raised as `HTTPException` in
`backend/app/routers/telemetry.py` and are not modeled here — FastAPI's
built-in `HTTPValidationError`/`detail`-based error shape is used for them
instead of a bespoke schema.

Validation ranges added here (latitude/longitude/battery/signal_strength/
cpu_load, plus the physically-motivated non-negativity of altitude and
velocity, and the absolute-zero floor on temperature) reject only values
that are already physically impossible for real telemetry — every value
the simulator currently generates falls comfortably inside these ranges.
`status` is intentionally left as a free-form string rather than an enum:
constraining it would reject values the API previously accepted, which is
a behavior change and out of scope here.
"""

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field

# Example payload reused across TelemetryCreate and TelemetryResponse so
# Swagger shows a consistent, realistic example everywhere.
_EXAMPLE_TELEMETRY = {
    "satellite_id": "SD-CUBESAT-001",
    "latitude": 8.9832,
    "longitude": -79.5199,
    "altitude": 408.42,
    "velocity": 7.66,
    "battery": 98.4,
    "temperature": 22.5,
    "signal_strength": 94.8,
    "cpu_load": 28.1,
    "status": "Nominal",
    "timestamp": "2026-07-27T18:35:12Z",
}


class TelemetryCreate(BaseModel):
    """
    A single telemetry packet, as generated by a satellite or by this
    project's telemetry simulator (`backend/simulator/telemetry_generator.py`).
    """

    satellite_id: str = Field(
        ...,
        min_length=1,
        description="Identifier of the satellite that generated this telemetry sample.",
        examples=["SD-CUBESAT-001"],
    )

    latitude: float = Field(
        ...,
        ge=-90,
        le=90,
        description="Sub-satellite point latitude, in decimal degrees (WGS84).",
        examples=[8.9832],
    )

    longitude: float = Field(
        ...,
        ge=-180,
        le=180,
        description="Sub-satellite point longitude, in decimal degrees (WGS84).",
        examples=[-79.5199],
    )

    altitude: float = Field(
        ...,
        ge=0,
        description="Altitude above the Earth's surface, in kilometers.",
        examples=[408.42],
    )

    velocity: float = Field(
        ...,
        ge=0,
        description="Orbital speed, in kilometers per second.",
        examples=[7.66],
    )

    battery: float = Field(
        ...,
        ge=0,
        le=100,
        description="Battery charge level, as a percentage.",
        examples=[98.4],
    )

    temperature: float = Field(
        ...,
        ge=-273.15,  # absolute zero — the only physically meaningful lower bound
        description="Onboard temperature, in degrees Celsius.",
        examples=[22.5],
    )

    signal_strength: float = Field(
        ...,
        ge=0,
        le=100,
        description="Downlink signal strength, as a percentage.",
        examples=[94.8],
    )

    cpu_load: float = Field(
        ...,
        ge=0,
        le=100,
        description="Onboard flight computer CPU load, as a percentage.",
        examples=[28.1],
    )

    status: str = Field(
        ...,
        description=(
            "Overall satellite health status. The project's frontend clients "
            'recognize "Nominal", "Warning", and "Critical", but this field '
            "is not enum-constrained at the API layer."
        ),
        examples=["Nominal"],
    )

    timestamp: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC timestamp when the sample was generated, in ISO 8601 format.",
        examples=["2026-07-27T18:35:12Z"],
    )

    model_config = ConfigDict(
        json_schema_extra={"examples": [_EXAMPLE_TELEMETRY]}
    )


class TelemetryCreatedResponse(BaseModel):
    """Response returned after a telemetry packet has been stored."""

    message: str = Field(
        ...,
        description="Human-readable confirmation message.",
        examples=["Telemetry stored successfully"],
    )
    id: int = Field(
        ...,
        description="Database identifier assigned to the newly stored telemetry record.",
        examples=[52],
    )

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [{"message": "Telemetry stored successfully", "id": 52}]
        }
    )


class TelemetryResponse(BaseModel):
    """A single stored telemetry record, as returned by `GET /telemetry/latest`."""

    id: int = Field(..., description="Database identifier of the telemetry record.", examples=[52])
    satellite_id: str = Field(..., description="Identifier of the satellite that generated this sample.", examples=["SD-CUBESAT-001"])
    latitude: float = Field(..., description="Sub-satellite point latitude, in decimal degrees.", examples=[8.9832])
    longitude: float = Field(..., description="Sub-satellite point longitude, in decimal degrees.", examples=[-79.5199])
    altitude: float = Field(..., description="Altitude above the Earth's surface, in kilometers.", examples=[408.42])
    velocity: float = Field(..., description="Orbital speed, in kilometers per second.", examples=[7.66])
    timestamp: datetime = Field(..., description="UTC timestamp when the sample was generated.", examples=["2026-07-27T18:35:12Z"])
    battery: float = Field(..., description="Battery charge level, as a percentage.", examples=[98.4])
    temperature: float = Field(..., description="Onboard temperature, in degrees Celsius.", examples=[22.5])
    signal_strength: float = Field(..., description="Downlink signal strength, as a percentage.", examples=[94.8])
    cpu_load: float = Field(..., description="Onboard flight computer CPU load, as a percentage.", examples=[28.1])
    status: str = Field(..., description="Overall satellite health status.", examples=["Nominal"])

    model_config = ConfigDict(
        json_schema_extra={"examples": [{"id": 52, **_EXAMPLE_TELEMETRY}]}
    )