"""

Pydantic schemas for the /telemetry endpoints.

`TelemetryCreate` is the request body accepted by `POST /telemetry`.

`TelemetryCreatedResponse` and `TelemetryResponse` describe the success

response shapes so Swagger/OpenAPI documents them precisely instead of

showing an untyped dict. Error responses (404 when no telemetry exists,

500 on a database failure) are raised as `HTTPException` in

`backend/app/routers/telemetry.py` and are not modeled here — FastAPI's

built-in `HTTPValidationError`/`detail`-based error shape is used for them

instead of a bespoke schema.

Validation ranges added here (latitude/longitude/battery/signal_strength/

cpu_load, plus the physically-motivated non-negativity of altitude and

velocity, and the absolute-zero floor on temperature) reject only values

that are already physically impossible for real telemetry — every value

the simulator currently generates falls comfortably inside these ranges.

`TelemetryCreate` has no `status` field: the client (the simulator, or any

future real satellite) reports `subsystems` — independent health for each

of the five subsystems in backend/app/core/health_status.py — and the

backend computes the single overall `status` from it via

`health_status.worst_status()`, in `backend/app/routers/telemetry.py`,

immediately before storing the record. A client-supplied overall status

would be a second, potentially-inconsistent source of truth for exactly

the same fact `subsystems` already reports; the backend is the only

place that fact is allowed to be decided. `TelemetryResponse` still

includes `status`, since it's a useful convenience field for read-only

consumers (the Chrome extension popup, the fleet card badge) that don't

need per-subsystem detail — it is always the backend's own computed value,

never client input.

"""

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field, ValidationInfo, field_validator

from backend.app.core.health_status import HealthStatus, SUBSYSTEMS

from backend.app.models.satellite_state import ComputerState, OperatingMode

from backend.app.schemas.alarms import Alarm

# Example payload reused across TelemetryCreate and TelemetryResponse so

# Swagger shows a consistent, realistic example everywhere.

_EXAMPLE_SUBSYSTEMS = {

    "power": "Nominal",

    "thermal": "Nominal",

    "communications": "Nominal",

    "adcs": "Nominal",

    "payload": "Nominal",

}

_EXAMPLE_TELEMETRY_CREATE = {

    "satellite_id": "SD-CUBESAT-001",

    "latitude": 8.9832,

    "longitude": -79.5199,

    "altitude": 408.42,

    "velocity": 7.66,

    "battery": 98.4,

    "temperature": 22.5,

    "signal_strength": 94.8,

    "cpu_load": 28.1,

    "subsystems": _EXAMPLE_SUBSYSTEMS,

    "timestamp": "2026-07-27T18:35:12Z",

}

_EXAMPLE_TELEMETRY_RESPONSE = {

    **_EXAMPLE_TELEMETRY_CREATE,

    "status": "Nominal",

}

class TelemetryCreate(BaseModel):

    """

    A single telemetry packet, as generated by a satellite or by this

    project's telemetry simulator (`backend/simulator/telemetry_generator.py`).

    Deliberately has no `status` field — see this module's docstring.

    """

    satellite_id: str = Field(

        ...,

        min_length=1,

        description="Identifier of the satellite that generated this telemetry sample.",

        examples=["SD-CUBESAT-001"],

    )

    latitude: float = Field(

        ...,

        ge=-90,

        le=90,

        description="Sub-satellite point latitude, in decimal degrees (WGS84).",

        examples=[8.9832],

    )

    longitude: float = Field(

        ...,

        ge=-180,

        le=180,

        description="Sub-satellite point longitude, in decimal degrees (WGS84).",

        examples=[-79.5199],

    )

    altitude: float = Field(

        ...,

        ge=0,

        description="Altitude above the Earth's surface, in kilometers.",

        examples=[408.42],

    )

    velocity: float = Field(

        ...,

        ge=0,

        description="Orbital speed, in kilometers per second.",

        examples=[7.66],

    )

    battery: float = Field(

        ...,

        ge=0,

        le=100,

        description="Battery charge level, as a percentage.",

        examples=[98.4],

    )

    temperature: float = Field(

        ...,

        ge=-273.15,  # absolute zero — the only physically meaningful lower bound

        description="Onboard temperature, in degrees Celsius.",

        examples=[22.5],

    )

    signal_strength: float = Field(

        ...,

        ge=0,

        le=100,

        description="Downlink signal strength, as a percentage.",

        examples=[94.8],

    )

    cpu_load: float = Field(

        ...,

        ge=0,

        le=100,

        description="Onboard flight computer CPU load, as a percentage.",

        examples=[28.1],

    )

    subsystems: dict[str, HealthStatus] = Field(

        ...,

        description=(

            "Independent health status for each of the five subsystems "

            "listed in backend/app/core/health_status.py (SUBSYSTEMS), "

            "keyed by subsystem name. This is the sole source of truth for "

            "satellite health at the API boundary — "

            "backend/app/core/alarms.py evaluates alarms from it directly, "

            "and backend/app/routers/telemetry.py computes the stored "

            "record's overall `status` from it via "

            "health_status.worst_status(). There is no separate `status` "

            "field on this request schema for a client to supply."

        ),

        examples=[_EXAMPLE_SUBSYSTEMS],

    )

    timestamp: datetime = Field(

        default_factory=datetime.utcnow,

        description="UTC timestamp when the sample was generated, in ISO 8601 format.",

        examples=["2026-07-27T18:35:12Z"],

    )

    @field_validator("subsystems")

    @classmethod

    def _validate_subsystem_keys(cls, value: dict[str, HealthStatus]) -> dict[str, HealthStatus]:

        """

        Rejects a `subsystems` dict with missing or unexpected keys, rather

        than silently accepting a partial or misspelled set — the same

        "reject what's already impossible" philosophy as the numeric range

        validation elsewhere in this schema.

        """

        expected = set(SUBSYSTEMS)

        actual = set(value.keys())

        if actual != expected:

            missing = sorted(expected - actual)

            unexpected = sorted(actual - expected)

            raise ValueError(

                f"subsystems must report exactly {sorted(expected)} — "

                f"missing: {missing or 'none'}, unexpected: {unexpected or 'none'}"

            )

        return value

    # --- Command Uplink state snapshot ----------------------------------

    # A snapshot of this satellite's commanded state (see

    # backend/app/models/satellite_state.py) at generation time — the

    # telemetry simulator fetches it from `GET /satellite-state/{id}`

    # before building each packet (see

    # backend/simulator/telemetry_generator.py) and includes it here, so a

    # command's effect (backend/app/core/commands.py) is observable in

    # subsequent telemetry, not only by separately querying

    # `GET /satellite-state/{id}`.

    # Optional, with defaults matching a satellite that has never received

    # a command (see backend/app/models/satellite_state.py's own

    # defaults): unlike `subsystems` above, these are not made required,

    # since a hypothetical telemetry producer other than this project's own

    # simulator (which is being updated in lockstep with this schema)

    # should not be forced to know about a feature unrelated to its own

    # telemetry.

    payload_enabled: bool = Field(

        False,

        description="Whether the payload is currently enabled — see the ENABLE_PAYLOAD command.",

        examples=[False],

    )

    operating_mode: OperatingMode = Field(

        OperatingMode.NOMINAL,

        description="Current commanded operating mode — see the CHANGE_MODE/ENTER_SAFE_MODE commands. Distinct from subsystem health status; see backend/app/models/satellite_state.py.",

        examples=["NOMINAL"],

    )

    computer_state: ComputerState = Field(

        ComputerState.NORMAL,

        description="Current flight-computer state — NORMAL, or RESTARTING during a simulated RESTART_COMPUTER command.",

        examples=["NORMAL"],

    )

    model_config = ConfigDict(

        json_schema_extra={"examples": [_EXAMPLE_TELEMETRY_CREATE]}

    )

class TelemetryCreatedResponse(BaseModel):

    """Response returned after a telemetry packet has been stored."""

    message: str = Field(

        ...,

        description="Human-readable confirmation message.",

        examples=["Telemetry stored successfully"],

    )

    id: int = Field(

        ...,

        description="Database identifier assigned to the newly stored telemetry record.",

        examples=[52],

    )

    model_config = ConfigDict(

        json_schema_extra={

            "examples": [{"message": "Telemetry stored successfully", "id": 52}]

        }

    )

class TelemetryResponse(BaseModel):

    """A single stored telemetry record, as returned by `GET /telemetry/latest`."""

    id: int = Field(..., description="Database identifier of the telemetry record.", examples=[52])

    satellite_id: str = Field(..., description="Identifier of the satellite that generated this sample.", examples=["SD-CUBESAT-001"])

    latitude: float = Field(..., description="Sub-satellite point latitude, in decimal degrees.", examples=[8.9832])

    longitude: float = Field(..., description="Sub-satellite point longitude, in decimal degrees.", examples=[-79.5199])

    altitude: float = Field(..., description="Altitude above the Earth's surface, in kilometers.", examples=[408.42])

    velocity: float = Field(..., description="Orbital speed, in kilometers per second.", examples=[7.66])

    timestamp: datetime = Field(..., description="UTC timestamp when the sample was generated.", examples=["2026-07-27T18:35:12Z"])

    battery: float = Field(..., description="Battery charge level, as a percentage.", examples=[98.4])

    temperature: float = Field(..., description="Onboard temperature, in degrees Celsius.", examples=[22.5])

    signal_strength: float = Field(..., description="Downlink signal strength, as a percentage.", examples=[94.8])

    cpu_load: float = Field(..., description="Onboard flight computer CPU load, as a percentage.", examples=[28.1])

    status: str = Field(

        ...,

        description=(

            "Overall satellite health status, computed by the backend as "

            "the worst of `subsystems` below (see "

            "health_status.worst_status(), called from "

            "backend/app/routers/telemetry.py) — never client-supplied. "

            "Provided as a convenience for consumers that don't need "

            "per-subsystem detail, such as the Chrome extension popup and "

            "the dashboard's fleet card badge."

        ),

        examples=["Nominal"],

    )

    subsystems: dict[str, HealthStatus] = Field(

        default_factory=dict,

        description=(

            "Independent health status for each of the five subsystems "

            "(see backend/app/core/health_status.py). Empty for telemetry "

            "records stored before this field existed — see "

            "`_default_missing_subsystems` below."

        ),

        examples=[_EXAMPLE_SUBSYSTEMS],

    )

    alarms: list[Alarm] = Field(

        default_factory=list,

        description=(

            "Alarms triggered by this telemetry sample, evaluated by "

            "backend/app/core/alarms.py. Empty when the sample is fully "

            "nominal. Populated on GET /telemetry/latest and on the "

            "WebSocket broadcast from POST /telemetry; defaults to an "

            "empty list elsewhere (GET /telemetry, GET /telemetry/history), "

            "which do not re-evaluate alarms for historical records."

        ),

        examples=[[]],

    )

    payload_enabled: bool = Field(

        False,

        description="Whether the payload was enabled at the time of this sample. False (the pre-ENABLE_PAYLOAD default) for records stored before this field existed.",

        examples=[False],

    )

    operating_mode: OperatingMode = Field(

        OperatingMode.NOMINAL,

        description="Commanded operating mode at the time of this sample. NOMINAL (the default) for records stored before this field existed.",

        examples=["NOMINAL"],

    )

    computer_state: ComputerState = Field(

        ComputerState.NORMAL,

        description="Flight-computer state at the time of this sample. NORMAL (the default) for records stored before this field existed.",

        examples=["NORMAL"],

    )

    @field_validator(

        "payload_enabled",

        "operating_mode",

        "computer_state",

        mode="before",

    )

    @classmethod

    def _default_missing_command_state(

        cls,

        value,

        info: ValidationInfo,

    ):

        """

        Same reasoning as `_default_missing_subsystems` below: telemetry

        rows stored before these three columns existed have them as `None`

        at the database level (backend/app/models/telemetry.py's

        `nullable=True`), which a plain field default alone would not

        catch, since the key is present but explicitly `None` rather than

        absent.

        Returns each field's own default (False / NOMINAL / NORMAL) by

        name via `info.field_name` — a single `mode="before"` validator

        shared across three fields has no other way to know which of them

        it's currently validating. An earlier version of this validator

        tried returning the `pydantic_core.PydanticUndefined` sentinel to

        mean "fall back to the field's default," which does not work: it

        is validated as a literal value against the field's declared type

        and fails (confirmed by testing, not assumed) — there is no

        built-in "use the default" signal a `mode="before"` validator can

        return; the default has to be supplied explicitly, as done here.

        """

        if value is not None:

            return value

        defaults = {

            "payload_enabled": False,

            "operating_mode": OperatingMode.NOMINAL,

            "computer_state": ComputerState.NORMAL,

        }

        return defaults[info.field_name]

    @field_validator("subsystems", mode="before")

    @classmethod

    def _default_missing_subsystems(cls, value):

        """

        Telemetry rows stored before the `subsystems` database column

        existed have `subsystems=None` at the database level (see

        backend/app/models/telemetry.py's `nullable=True`) rather than

        simply lacking the attribute, so `default_factory` alone — which

        only applies when a key is absent entirely — wouldn't catch this.

        Coerced to an empty dict here instead, matching the same

        "historical records show no data for a field added later" pattern

        already used for `alarms` above.

        """

        return value if value is not None else {}

    model_config = ConfigDict(

        json_schema_extra={"examples": [{"id": 52, "alarms": [], **_EXAMPLE_TELEMETRY_RESPONSE}]}

    )